### PR TITLE
Tim method transform

### PR DESCRIPTION
**Pull request by sharmistharanit**
Please see the updation by professor

### CODE REVIEW

**Review by AhmedCode99 — COMMENTED** [review]
Please explain why you made these changes

**Comment by sharmistharanit** [comment]
In the previous file, you did not define any function which I will call for unit testing. That's why Professor used a function.

**Comment by sharmistharanit** [comment]
He suggested to choose an easier example so that I could write a unit test for that. Otherwise, you have to update the code. We can sit together and make it. However, as we have a very short time it will be easier if we choose another hw. What do you think? @AhmedCode99 @yasmensarhan27

**Comment by AhmedCode99** [comment]
rejected

**Comment by sharmistharanit** [comment]
What do you mean by that?

**Comment by AhmedCode99** [comment]
You just insignificantly changed Dr. Thomay's code, by changing every version. For example, you change Python 3.10 to 3.8. And so on, which does not improve the code.

Then you added a greeting code we did in class, and there is like a day left in the assignment.

Good effort, but unrequired. Please focus on writing a test.py file containing a pytest unit test. Which is what is required.

Rejected

**Comment by sharmistharanit** [comment]
I am asking to check professor's code not mine.

**Review by AhmedCode99 — COMMENTED** [review]
what is the reason for these changes?

**Comment by AhmedCode99** [comment]
I am not sure what you are talking about. It is all your code, Dr. Thomay did not submit a pull request. Your branch is conflicting with the main branch, I am trying to figure out what you did. But I just cant.

Maybe divide your request into smaller more readable requests.

**Pull request closed without merging**
